services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    ports:
      - '5015:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=casedb;Username=postgres;Password=postgres;Pooling=true;MinPoolSize=0;MaxPoolSize=100;ConnectionIdleLifetime=300;
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 5
