services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #     network: host
  #   ports:
  #     - '5015:8080'
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Host=postgres;Database=casedb;Username=postgres;Password=postgres;Pooling=true;MinPoolSize=0;MaxPoolSize=100;ConnectionIdleLifetime=300;

  postgres:
    image: postgres:17.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: casedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8888:8080

  # nuxt:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   environment:
  #     - NITRO_PORT=5173
  #     - NODE_ENV=production
  #     - API_URL=http://backend:8080
  #   depends_on:
  #     - backend
  #   ports:
  #     - '5173:5173'

  # nginx:
  #   image: nginx:1.24.0
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - '80:80'
  #   environment:
  #     - NGINX_PORT=80
  #   depends_on:
  #     - nuxt

volumes:
  postgres:
