services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    ports:
      - '5015:8080'
    environment:
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=casedb;Username=postgres;Password=postgres;Pooling=true;MinPoolSize=0;MaxPoolSize=100;ConnectionIdleLifetime=300;

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    depends_on:
      backend:
